package project.manager.handlers;

public enum Endpoint {
    GET_TASK,
    GET_TASKS,
    POST_ADD_TASK,
    POST_UPDATE_TASK,
    DELETE_TASK,
    GET_SUBTASK,
    GET_SUBTASKS,
    POST_ADD_SUBTASK,
    POST_UPDATE_SUBTASK,
    DELETE_SUBTASK,
    GET_EPIC,
    GET_EPICS,
    GET_EPIC_SUBTASKS,
    POST_ADD_EPIC,
    POST_UPDATE_EPIC,
    DELETE_EPIC,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    UNKNOWN
}
